name: Test Terraform
on:
  - pull_request

jobs:
  e2e-tests:
    name: Run e2e test
    runs-on: ubuntu-latest
    # build-tools is built from ../../tools/build-tools.Dockerfile
    container: ghcr.io/kedacore/build-tools:1.18.6
    concurrency: e2e-tests
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Register workspace path
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(secrets) }}

      - name: Run end to end tests
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_RUN_IDENTITY_TESTS: true
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
          TF_AZURE_APP_INSIGHTS_APP_ID: ${{ secrets.TF_AZURE_APP_INSIGHTS_APP_ID }}
          TF_AZURE_APP_INSIGHTS_CONNECTION_STRING: ${{ secrets.TF_AZURE_APP_INSIGHTS_CONNECTION_STRING }}
          TF_AZURE_APP_INSIGHTS_INSTRUMENTATION_KEY: ${{ secrets.TF_AZURE_APP_INSIGHTS_INSTRUMENTATION_KEY }}
          TF_AZURE_DATA_EXPLORER_DB: ${{ secrets.TF_AZURE_DATA_EXPLORER_DB }}
          TF_AZURE_DATA_EXPLORER_ENDPOINT: ${{ secrets.TF_AZURE_DATA_EXPLORER_ENDPOINT }}
          AZURE_DEVOPS_BUILD_DEFINITION_ID: ${{ secrets.AZURE_DEVOPS_BUILD_DEFINITION_ID }}
          AZURE_DEVOPS_ORGANIZATION_URL: ${{ secrets.AZURE_DEVOPS_ORGANIZATION_URL }}
          AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
          AZURE_DEVOPS_POOL_NAME: ${{ secrets.AZURE_DEVOPS_POOL_NAME }}
          AZURE_DEVOPS_PROJECT: ${{ secrets.AZURE_DEVOPS_PROJECT }}
          TF_AZURE_EVENTHBUS_MANAGEMENT_CONNECTION_STRING : ${{ secrets.TF_AZURE_EVENTHBUS_MANAGEMENT_CONNECTION_STRING }}
          TF_AZURE_KEYVAULT_URI:  ${{ secrets.TF_AZURE_KEYVAULT_URI }}
          TF_AZURE_LOG_ANALYTICS_WORKSPACE_ID: ${{ secrets.TF_AZURE_LOG_ANALYTICS_WORKSPACE_ID }}
          TF_AZURE_RESOURCE_GROUP: ${{ secrets.TF_AZURE_RESOURCE_GROUP }}
          AZURE_RUN_WORKLOAD_IDENTITY_TESTS: true
          TF_AZURE_SERVICE_BUS_CONNECTION_STRING:  ${{ secrets.TF_AZURE_SERVICE_BUS_CONNECTION_STRING }}
          TF_AZURE_SERVICE_BUS_ALTERNATIVE_CONNECTION_STRING:  ${{ secrets.TF_AZURE_SERVICE_BUS_ALTERNATIVE_CONNECTION_STRING }}
          TF_AZURE_SP_APP_ID: ${{ secrets.TF_AZURE_SP_APP_ID }}
          TF_AZURE_SP_OBJECT_ID: ${{ secrets.TF_AZURE_SP_OBJECT_ID }}
          TF_AZURE_SP_KEY: ${{ secrets.TF_AZURE_SP_KEY }}
          TF_AZURE_SP_ALTERNATIVE_APP_ID: ${{ secrets.TF_AZURE_SP_ALTERNATIVE_APP_ID }}
          TF_AZURE_SP_TENANT: ${{ secrets.TF_AZURE_SP_TENANT }}
          TF_AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.TF_AZURE_STORAGE_CONNECTION_STRING }}
          TF_AZURE_SUBSCRIPTION: ${{ secrets.TF_AZURE_SUBSCRIPTION }}
          DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY}}
          DATADOG_APP_KEY: ${{ secrets.DATADOG_APP_KEY}}
          DATADOG_SITE: ${{ secrets.DATADOG_SITE}}
          GCP_SP_KEY: ${{ secrets.GCP_SP_KEY }}
          NEWRELIC_ACCOUNT_ID: ${{ secrets.NEWRELIC_ACCOUNT_ID}}
          NEWRELIC_API_KEY: ${{ secrets.NEWRELIC_API_KEY}}
          NEWRELIC_LICENSE: ${{ secrets.NEWRELIC_LICENSE}}
          OIDC_ISSUER_URL: ${{ secrets.OIDC_ISSUER_URLNIGHTLY }}
          OPENSTACK_AUTH_URL: ${{ secrets.OPENSTACK_AUTH_URL }}
          OPENSTACK_PASSWORD: ${{ secrets.OPENSTACK_PASSWORD }}
          OPENSTACK_PROJECT_ID: ${{ secrets.OPENSTACK_PROJECT_ID }}
          OPENSTACK_USER_ID: ${{ secrets.OPENSTACK_USER_ID }}
          PREDICTKUBE_API_KEY: ${{ secrets.PREDICTKUBE_API_KEY }}
        run: make e2e-test

      - name: Delete all e2e related namespaces
        if: ${{ always() }}
        run: make e2e-test-clean
        env:
          TF_AZURE_RESOURCE_GROUP: ${{ secrets.TF_AZURE_RESOURCE_GROUP }}
          TF_AZURE_SP_APP_ID: ${{ secrets.TF_AZURE_SP_APP_ID }}
          TF_AZURE_SP_KEY: ${{ secrets.TF_AZURE_SP_KEY }}
          TF_AZURE_SP_TENANT: ${{ secrets.TF_AZURE_SP_TENANT }}
          TF_AZURE_SUBSCRIPTION: ${{ secrets.TF_AZURE_SUBSCRIPTION }}
